//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jump.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("es-ES")]
        public string IdiomaDelPrograma {
            get {
                return ((string)(this["IdiomaDelPrograma"]));
            }
            set {
                this["IdiomaDelPrograma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ConfiguracionPrecisionOrdenarX {
            get {
                return ((double)(this["ConfiguracionPrecisionOrdenarX"]));
            }
            set {
                this["ConfiguracionPrecisionOrdenarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ZapataIndiceComboboxEscalaVista {
            get {
                return ((int)(this["ZapataIndiceComboboxEscalaVista"]));
            }
            set {
                this["ZapataIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraEnumeracionPorElemento {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorElemento"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorElemento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraEnumeracionPorProyecto {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorProyecto"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorProyecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraDibujoLineasCentrales {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasCentrales"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasCentrales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraDibujoLineasBorde {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasBorde"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasBorde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfiguracionVistaLocal {
            get {
                return ((bool)(this["ConfiguracionVistaLocal"]));
            }
            set {
                this["ConfiguracionVistaLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfiguracionVistaGlobal {
            get {
                return ((bool)(this["ConfiguracionVistaGlobal"]));
            }
            set {
                this["ConfiguracionVistaGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ConfiguracionPrecisionOrdenarY {
            get {
                return ((double)(this["ConfiguracionPrecisionOrdenarY"]));
            }
            set {
                this["ConfiguracionPrecisionOrdenarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PosicionBarraADibujar {
            get {
                return ((int)(this["PosicionBarraADibujar"]));
            }
            set {
                this["PosicionBarraADibujar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActualizarBarrasAutomaticamente {
            get {
                return ((bool)(this["ActualizarBarrasAutomaticamente"]));
            }
            set {
                this["ActualizarBarrasAutomaticamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnTextoArmaduraArriba {
            get {
                return ((bool)(this["rbtnTextoArmaduraArriba"]));
            }
            set {
                this["rbtnTextoArmaduraArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnTextoArmaduraAbajo {
            get {
                return ((bool)(this["rbtnTextoArmaduraAbajo"]));
            }
            set {
                this["rbtnTextoArmaduraAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ZapataCorridaEtiquetaIndependiente {
            get {
                return ((int)(this["ZapataCorridaEtiquetaIndependiente"]));
            }
            set {
                this["ZapataCorridaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PlateaEtiquetaIndependiente {
            get {
                return ((int)(this["PlateaEtiquetaIndependiente"]));
            }
            set {
                this["PlateaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MuroEtiquetaIndependiente {
            get {
                return ((int)(this["MuroEtiquetaIndependiente"]));
            }
            set {
                this["MuroEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PiloteEtiquetaIndependiente {
            get {
                return ((int)(this["PiloteEtiquetaIndependiente"]));
            }
            set {
                this["PiloteEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ArmaduraEtiquetaIndependiente {
            get {
                return ((int)(this["ArmaduraEtiquetaIndependiente"]));
            }
            set {
                this["ArmaduraEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int VigaEtiquetaIndependiente {
            get {
                return ((int)(this["VigaEtiquetaIndependiente"]));
            }
            set {
                this["VigaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ZapataEtiquetaIndependiente {
            get {
                return ((int)(this["ZapataEtiquetaIndependiente"]));
            }
            set {
                this["ZapataEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ColumnaCotaProfundidad {
            get {
                return ((int)(this["ColumnaCotaProfundidad"]));
            }
            set {
                this["ColumnaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnaEtiquetaIndependiente {
            get {
                return ((int)(this["ColumnaEtiquetaIndependiente"]));
            }
            set {
                this["ColumnaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LosaEtiquetaIndependiente {
            get {
                return ((int)(this["LosaEtiquetaIndependiente"]));
            }
            set {
                this["LosaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AreaRefuerzoEtiquetaIndependiente {
            get {
                return ((int)(this["AreaRefuerzoEtiquetaIndependiente"]));
            }
            set {
                this["AreaRefuerzoEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ArmaduraEnSistemaEtiquetaIndependiente {
            get {
                return ((int)(this["ArmaduraEnSistemaEtiquetaIndependiente"]));
            }
            set {
                this["ArmaduraEnSistemaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double toleranciaSuperposicionArmadura {
            get {
                return ((double)(this["toleranciaSuperposicionArmadura"]));
            }
            set {
                this["toleranciaSuperposicionArmadura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ColumnaIndiceComboboxEscalaVista {
            get {
                return ((int)(this["ColumnaIndiceComboboxEscalaVista"]));
            }
            set {
                this["ColumnaIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int VigaIndiceComboboxEscalaVista {
            get {
                return ((int)(this["VigaIndiceComboboxEscalaVista"]));
            }
            set {
                this["VigaIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LosaCotaProfundidad {
            get {
                return ((int)(this["LosaCotaProfundidad"]));
            }
            set {
                this["LosaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MuroCotaProfundidad {
            get {
                return ((int)(this["MuroCotaProfundidad"]));
            }
            set {
                this["MuroCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int PlateaCotaProfundidad {
            get {
                return ((int)(this["PlateaCotaProfundidad"]));
            }
            set {
                this["PlateaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int VigaCotaProfundidad {
            get {
                return ((int)(this["VigaCotaProfundidad"]));
            }
            set {
                this["VigaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ZapataCotaProfundidad {
            get {
                return ((int)(this["ZapataCotaProfundidad"]));
            }
            set {
                this["ZapataCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ZapataCorridaCotaProfundidad {
            get {
                return ((int)(this["ZapataCorridaCotaProfundidad"]));
            }
            set {
                this["ZapataCorridaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MuroIndiceComboboxEscalaVista {
            get {
                return ((int)(this["MuroIndiceComboboxEscalaVista"]));
            }
            set {
                this["MuroIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string ZapataCorridaIndiceComboboxEscalaVista {
            get {
                return ((string)(this["ZapataCorridaIndiceComboboxEscalaVista"]));
            }
            set {
                this["ZapataCorridaIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int PiloteCotaProfundidad {
            get {
                return ((int)(this["PiloteCotaProfundidad"]));
            }
            set {
                this["PiloteCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PiloteCotaLinealArriba {
            get {
                return ((bool)(this["PiloteCotaLinealArriba"]));
            }
            set {
                this["PiloteCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PiloteCotaLinealAbajo {
            get {
                return ((bool)(this["PiloteCotaLinealAbajo"]));
            }
            set {
                this["PiloteCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PiloteCotaLinealIzquierda {
            get {
                return ((bool)(this["PiloteCotaLinealIzquierda"]));
            }
            set {
                this["PiloteCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PiloteCotaLinealDerecha {
            get {
                return ((bool)(this["PiloteCotaLinealDerecha"]));
            }
            set {
                this["PiloteCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VigaCotaLinealArriba {
            get {
                return ((bool)(this["VigaCotaLinealArriba"]));
            }
            set {
                this["VigaCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VigaCotaLinealAbajo {
            get {
                return ((bool)(this["VigaCotaLinealAbajo"]));
            }
            set {
                this["VigaCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VigaCotaLinealIzquierda {
            get {
                return ((bool)(this["VigaCotaLinealIzquierda"]));
            }
            set {
                this["VigaCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VigaCotaLinealDerecha {
            get {
                return ((bool)(this["VigaCotaLinealDerecha"]));
            }
            set {
                this["VigaCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnaCotaLinealArriba {
            get {
                return ((bool)(this["ColumnaCotaLinealArriba"]));
            }
            set {
                this["ColumnaCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnaCotaLinealAbajo {
            get {
                return ((bool)(this["ColumnaCotaLinealAbajo"]));
            }
            set {
                this["ColumnaCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnaCotaLinealIzquierda {
            get {
                return ((bool)(this["ColumnaCotaLinealIzquierda"]));
            }
            set {
                this["ColumnaCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnaCotaLinealDerecha {
            get {
                return ((bool)(this["ColumnaCotaLinealDerecha"]));
            }
            set {
                this["ColumnaCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuroCotaLinealArriba {
            get {
                return ((bool)(this["MuroCotaLinealArriba"]));
            }
            set {
                this["MuroCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuroCotaLinealAbajo {
            get {
                return ((bool)(this["MuroCotaLinealAbajo"]));
            }
            set {
                this["MuroCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuroCotaLinealIzquierda {
            get {
                return ((bool)(this["MuroCotaLinealIzquierda"]));
            }
            set {
                this["MuroCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuroCotaLinealDerecha {
            get {
                return ((bool)(this["MuroCotaLinealDerecha"]));
            }
            set {
                this["MuroCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LosaCotaLinealArriba {
            get {
                return ((bool)(this["LosaCotaLinealArriba"]));
            }
            set {
                this["LosaCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LosaCotaLinealAbajo {
            get {
                return ((bool)(this["LosaCotaLinealAbajo"]));
            }
            set {
                this["LosaCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LosaCotaLinealIzquierda {
            get {
                return ((bool)(this["LosaCotaLinealIzquierda"]));
            }
            set {
                this["LosaCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LosaCotaLinealDerecha {
            get {
                return ((bool)(this["LosaCotaLinealDerecha"]));
            }
            set {
                this["LosaCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCotaLinealArriba {
            get {
                return ((bool)(this["ZapataCotaLinealArriba"]));
            }
            set {
                this["ZapataCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCotaLinealAbajo {
            get {
                return ((bool)(this["ZapataCotaLinealAbajo"]));
            }
            set {
                this["ZapataCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCotaLinealIzquierda {
            get {
                return ((bool)(this["ZapataCotaLinealIzquierda"]));
            }
            set {
                this["ZapataCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCotaLinealDerecha {
            get {
                return ((bool)(this["ZapataCotaLinealDerecha"]));
            }
            set {
                this["ZapataCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCorridaCotaLinealArriba {
            get {
                return ((bool)(this["ZapataCorridaCotaLinealArriba"]));
            }
            set {
                this["ZapataCorridaCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCorridaCotaLinealAbajo {
            get {
                return ((bool)(this["ZapataCorridaCotaLinealAbajo"]));
            }
            set {
                this["ZapataCorridaCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCorridaCotaLinealIzquierda {
            get {
                return ((bool)(this["ZapataCorridaCotaLinealIzquierda"]));
            }
            set {
                this["ZapataCorridaCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZapataCorridaCotaLinealDerecha {
            get {
                return ((bool)(this["ZapataCorridaCotaLinealDerecha"]));
            }
            set {
                this["ZapataCorridaCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlateaCotaLinealArriba {
            get {
                return ((bool)(this["PlateaCotaLinealArriba"]));
            }
            set {
                this["PlateaCotaLinealArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlateaCotaLinealAbajo {
            get {
                return ((bool)(this["PlateaCotaLinealAbajo"]));
            }
            set {
                this["PlateaCotaLinealAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlateaCotaLinealIzquierda {
            get {
                return ((bool)(this["PlateaCotaLinealIzquierda"]));
            }
            set {
                this["PlateaCotaLinealIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlateaCotaLinealDerecha {
            get {
                return ((bool)(this["PlateaCotaLinealDerecha"]));
            }
            set {
                this["PlateaCotaLinealDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double ConfiguracionPrecisionNodoAnalitico {
            get {
                return ((double)(this["ConfiguracionPrecisionNodoAnalitico"]));
            }
            set {
                this["ConfiguracionPrecisionNodoAnalitico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int ConfiguracionPrecisionAnguloPositivo {
            get {
                return ((int)(this["ConfiguracionPrecisionAnguloPositivo"]));
            }
            set {
                this["ConfiguracionPrecisionAnguloPositivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-45")]
        public int ConfiguracionPrecisionAnguloNegativo {
            get {
                return ((int)(this["ConfiguracionPrecisionAnguloNegativo"]));
            }
            set {
                this["ConfiguracionPrecisionAnguloNegativo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ConfiguracionCorteTransversalBasadoLinea {
            get {
                return ((double)(this["ConfiguracionCorteTransversalBasadoLinea"]));
            }
            set {
                this["ConfiguracionCorteTransversalBasadoLinea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ConfiguracionPuntoParaEvaluarLinea {
            get {
                return ((double)(this["ConfiguracionPuntoParaEvaluarLinea"]));
            }
            set {
                this["ConfiguracionPuntoParaEvaluarLinea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ConfiguracionPrecisionOrdenarZ {
            get {
                return ((double)(this["ConfiguracionPrecisionOrdenarZ"]));
            }
            set {
                this["ConfiguracionPrecisionOrdenarZ"] = value;
            }
        }
    }
}
