//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jump.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Español")]
        public string IdiomaDelPrograma {
            get {
                return ((string)(this["IdiomaDelPrograma"]));
            }
            set {
                this["IdiomaDelPrograma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int precisionOrdenarX {
            get {
                return ((int)(this["precisionOrdenarX"]));
            }
            set {
                this["precisionOrdenarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int zapataIndiceComboboxEscalaVista {
            get {
                return ((int)(this["zapataIndiceComboboxEscalaVista"]));
            }
            set {
                this["zapataIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraEnumeracionPorElemento {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorElemento"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorElemento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraEnumeracionPorProyecto {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorProyecto"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorProyecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraDibujoLineasCentrales {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasCentrales"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasCentrales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraDibujoLineasBorde {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasBorde"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasBorde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnGeneralVistaLocal {
            get {
                return ((bool)(this["rbtnGeneralVistaLocal"]));
            }
            set {
                this["rbtnGeneralVistaLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnGeneralVistaGlobal {
            get {
                return ((bool)(this["rbtnGeneralVistaGlobal"]));
            }
            set {
                this["rbtnGeneralVistaGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int precisionOrdenarY {
            get {
                return ((int)(this["precisionOrdenarY"]));
            }
            set {
                this["precisionOrdenarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int posicionBarraADibujar {
            get {
                return ((int)(this["posicionBarraADibujar"]));
            }
            set {
                this["posicionBarraADibujar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActualizarBarrasAutomaticamente {
            get {
                return ((bool)(this["ActualizarBarrasAutomaticamente"]));
            }
            set {
                this["ActualizarBarrasAutomaticamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int zapataIndiceComboboxTextoBarra {
            get {
                return ((int)(this["zapataIndiceComboboxTextoBarra"]));
            }
            set {
                this["zapataIndiceComboboxTextoBarra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaVerticalIzquierda {
            get {
                return ((bool)(this["CotaVerticalIzquierda"]));
            }
            set {
                this["CotaVerticalIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaVerticalDerecha {
            get {
                return ((bool)(this["CotaVerticalDerecha"]));
            }
            set {
                this["CotaVerticalDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaHorizontalAbajo {
            get {
                return ((bool)(this["CotaHorizontalAbajo"]));
            }
            set {
                this["CotaHorizontalAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaHorizontalArriba {
            get {
                return ((bool)(this["CotaHorizontalArriba"]));
            }
            set {
                this["CotaHorizontalArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnTextoArmaduraArriba {
            get {
                return ((bool)(this["rbtnTextoArmaduraArriba"]));
            }
            set {
                this["rbtnTextoArmaduraArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnTextoArmaduraAbajo {
            get {
                return ((bool)(this["rbtnTextoArmaduraAbajo"]));
            }
            set {
                this["rbtnTextoArmaduraAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteZapatasCorrida {
            get {
                return ((int)(this["EtiquetaIndependienteZapatasCorrida"]));
            }
            set {
                this["EtiquetaIndependienteZapatasCorrida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependientePlatea {
            get {
                return ((int)(this["EtiquetaIndependientePlatea"]));
            }
            set {
                this["EtiquetaIndependientePlatea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteMuros {
            get {
                return ((int)(this["EtiquetaIndependienteMuros"]));
            }
            set {
                this["EtiquetaIndependienteMuros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependientePilotes {
            get {
                return ((int)(this["EtiquetaIndependientePilotes"]));
            }
            set {
                this["EtiquetaIndependientePilotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EtiquetaIndependienteArmadura {
            get {
                return ((int)(this["EtiquetaIndependienteArmadura"]));
            }
            set {
                this["EtiquetaIndependienteArmadura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EtiquetaIndependienteVigas {
            get {
                return ((int)(this["EtiquetaIndependienteVigas"]));
            }
            set {
                this["EtiquetaIndependienteVigas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EtiquetaIndependienteZapatas {
            get {
                return ((int)(this["EtiquetaIndependienteZapatas"]));
            }
            set {
                this["EtiquetaIndependienteZapatas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int EtiquetaCotaProfundidad {
            get {
                return ((int)(this["EtiquetaCotaProfundidad"]));
            }
            set {
                this["EtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteColumnas {
            get {
                return ((int)(this["EtiquetaIndependienteColumnas"]));
            }
            set {
                this["EtiquetaIndependienteColumnas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteLosas {
            get {
                return ((int)(this["EtiquetaIndependienteLosas"]));
            }
            set {
                this["EtiquetaIndependienteLosas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteAreaRefuerzo {
            get {
                return ((int)(this["EtiquetaIndependienteAreaRefuerzo"]));
            }
            set {
                this["EtiquetaIndependienteAreaRefuerzo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EtiquetaIndependienteArmaduraEnSistema {
            get {
                return ((int)(this["EtiquetaIndependienteArmaduraEnSistema"]));
            }
            set {
                this["EtiquetaIndependienteArmaduraEnSistema"] = value;
            }
        }
    }
}
