//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jump.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Español")]
        public string IdiomaDelPrograma {
            get {
                return ((string)(this["IdiomaDelPrograma"]));
            }
            set {
                this["IdiomaDelPrograma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int precisionOrdenarX {
            get {
                return ((int)(this["precisionOrdenarX"]));
            }
            set {
                this["precisionOrdenarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZapatasIndiceComboboxEscalaVista {
            get {
                return ((int)(this["ZapatasIndiceComboboxEscalaVista"]));
            }
            set {
                this["ZapatasIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraEnumeracionPorElemento {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorElemento"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorElemento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraEnumeracionPorProyecto {
            get {
                return ((bool)(this["rbtnArmaduraEnumeracionPorProyecto"]));
            }
            set {
                this["rbtnArmaduraEnumeracionPorProyecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnArmaduraDibujoLineasCentrales {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasCentrales"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasCentrales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnArmaduraDibujoLineasBorde {
            get {
                return ((bool)(this["rbtnArmaduraDibujoLineasBorde"]));
            }
            set {
                this["rbtnArmaduraDibujoLineasBorde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnGeneralVistaLocal {
            get {
                return ((bool)(this["rbtnGeneralVistaLocal"]));
            }
            set {
                this["rbtnGeneralVistaLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnGeneralVistaGlobal {
            get {
                return ((bool)(this["rbtnGeneralVistaGlobal"]));
            }
            set {
                this["rbtnGeneralVistaGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int precisionOrdenarY {
            get {
                return ((int)(this["precisionOrdenarY"]));
            }
            set {
                this["precisionOrdenarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int posicionBarraADibujar {
            get {
                return ((int)(this["posicionBarraADibujar"]));
            }
            set {
                this["posicionBarraADibujar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActualizarBarrasAutomaticamente {
            get {
                return ((bool)(this["ActualizarBarrasAutomaticamente"]));
            }
            set {
                this["ActualizarBarrasAutomaticamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int indiceComboboxTextoBarra {
            get {
                return ((int)(this["indiceComboboxTextoBarra"]));
            }
            set {
                this["indiceComboboxTextoBarra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaVerticalIzquierda {
            get {
                return ((bool)(this["CotaVerticalIzquierda"]));
            }
            set {
                this["CotaVerticalIzquierda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaVerticalDerecha {
            get {
                return ((bool)(this["CotaVerticalDerecha"]));
            }
            set {
                this["CotaVerticalDerecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaHorizontalAbajo {
            get {
                return ((bool)(this["CotaHorizontalAbajo"]));
            }
            set {
                this["CotaHorizontalAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CotaHorizontalArriba {
            get {
                return ((bool)(this["CotaHorizontalArriba"]));
            }
            set {
                this["CotaHorizontalArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbtnTextoArmaduraArriba {
            get {
                return ((bool)(this["rbtnTextoArmaduraArriba"]));
            }
            set {
                this["rbtnTextoArmaduraArriba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rbtnTextoArmaduraAbajo {
            get {
                return ((bool)(this["rbtnTextoArmaduraAbajo"]));
            }
            set {
                this["rbtnTextoArmaduraAbajo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ZapatasCorridaEtiquetaIndependiente {
            get {
                return ((int)(this["ZapatasCorridaEtiquetaIndependiente"]));
            }
            set {
                this["ZapatasCorridaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PlateaEtiquetaIndependiente {
            get {
                return ((int)(this["PlateaEtiquetaIndependiente"]));
            }
            set {
                this["PlateaEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MurosEtiquetaIndependiente {
            get {
                return ((int)(this["MurosEtiquetaIndependiente"]));
            }
            set {
                this["MurosEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PilotesEtiquetaIndependiente {
            get {
                return ((int)(this["PilotesEtiquetaIndependiente"]));
            }
            set {
                this["PilotesEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EtiquetaIndependienteArmadura {
            get {
                return ((int)(this["EtiquetaIndependienteArmadura"]));
            }
            set {
                this["EtiquetaIndependienteArmadura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int VigasEtiquetaIndependiente {
            get {
                return ((int)(this["VigasEtiquetaIndependiente"]));
            }
            set {
                this["VigasEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ZapatasEtiquetaIndependiente {
            get {
                return ((int)(this["ZapatasEtiquetaIndependiente"]));
            }
            set {
                this["ZapatasEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ColumnasEtiquetaCotaProfundidad {
            get {
                return ((int)(this["ColumnasEtiquetaCotaProfundidad"]));
            }
            set {
                this["ColumnasEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ColumnasEtiquetaIndependiente {
            get {
                return ((int)(this["ColumnasEtiquetaIndependiente"]));
            }
            set {
                this["ColumnasEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LosasEtiquetaIndependiente {
            get {
                return ((int)(this["LosasEtiquetaIndependiente"]));
            }
            set {
                this["LosasEtiquetaIndependiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EtiquetaIndependienteAreaRefuerzo {
            get {
                return ((int)(this["EtiquetaIndependienteAreaRefuerzo"]));
            }
            set {
                this["EtiquetaIndependienteAreaRefuerzo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EtiquetaIndependienteArmaduraEnSistema {
            get {
                return ((int)(this["EtiquetaIndependienteArmaduraEnSistema"]));
            }
            set {
                this["EtiquetaIndependienteArmaduraEnSistema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double toleranciaSuperposicionArmadura {
            get {
                return ((double)(this["toleranciaSuperposicionArmadura"]));
            }
            set {
                this["toleranciaSuperposicionArmadura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnaIndiceComboboxEscalaVista {
            get {
                return ((int)(this["ColumnaIndiceComboboxEscalaVista"]));
            }
            set {
                this["ColumnaIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VigasIndiceComboboxEscalaVista {
            get {
                return ((int)(this["VigasIndiceComboboxEscalaVista"]));
            }
            set {
                this["VigasIndiceComboboxEscalaVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LosasEtiquetaCotaProfundidad {
            get {
                return ((int)(this["LosasEtiquetaCotaProfundidad"]));
            }
            set {
                this["LosasEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MurosEtiquetaCotaProfundidad {
            get {
                return ((int)(this["MurosEtiquetaCotaProfundidad"]));
            }
            set {
                this["MurosEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PlateaEtiquetaCotaProfundidad {
            get {
                return ((int)(this["PlateaEtiquetaCotaProfundidad"]));
            }
            set {
                this["PlateaEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int VigasEtiquetaCotaProfundidad {
            get {
                return ((int)(this["VigasEtiquetaCotaProfundidad"]));
            }
            set {
                this["VigasEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ZapatasEtiquetaCotaProfundidad {
            get {
                return ((int)(this["ZapatasEtiquetaCotaProfundidad"]));
            }
            set {
                this["ZapatasEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ZapatasCorridaEtiquetaCotaProfundidad {
            get {
                return ((int)(this["ZapatasCorridaEtiquetaCotaProfundidad"]));
            }
            set {
                this["ZapatasCorridaEtiquetaCotaProfundidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MurosIndiceComboboxEscalaVista {
            get {
                return ((int)(this["MurosIndiceComboboxEscalaVista"]));
            }
            set {
                this["MurosIndiceComboboxEscalaVista"] = value;
            }
        }
    }
}
